[workspace]
resolver = "2"
members = [
    "cargo-files",
    "cargo-files-core",
    "cargo-files-test"
]


[profile.dev.package.syn]
opt-level = 3

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
